### ISSUE TITLE
cudf installation is not working 

### ISSUE THREAD

**Issue by sparta0000** [rapidsai-community/showcase#19]
!pip install cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com

#Older documentation included these steps to reintall cupy, but this is no longer necessary since Rapids 22.12
#!rm -rf /usr/local/lib/python3.8/dist-packages/cupy*
#!pip install cupy-cuda11x

It is giving error :
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://pypi.ngc.nvidia.com/
Collecting cudf-cu11
  Using cached cudf_cu11-23.2.0.tar.gz (6.5 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by taureandyernv** [comment]
hey @sparta0000 FYI: as this has to do with deployment, this is the appropriate repo: https://github.com/rapidsai/deployment/issues, unless the issue has to do with the notebooks found in the repo.  

However, let me help:

You're pulling an older version of the wheels, which may be why you're having these issues.  please use this one: 
`pip install cudf-cu11 cuml-cu11 cugraph-cu11 aiohttp --extra-index-url=https://pypi.nvidia.com`.  Please refer to our deployment docs, https://docs.rapids.ai/install#pip, or our quick start guide, https://rapids.ai/#quick-start, or for the latest way to install RAPIDS via pip.
